### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by BharatKalluri** [AlbertExtensions/Ideas#15]
An extension to correct the wrong spelling from Albert. Could use an API like Grammar Bot or Bing's spell check as a data source.

**Comment by abers** [comment]
There's also ispell/aspell that comes pre-installed on most Linux distros and don't require internet access. Be handy if could also search for definitions / thesaurus feature similar to [Artha](https://sourceforge.net/projects/artha/).

**Comment by BharatKalluri** [comment]
https://github.com/AlbertExtensions/spell solves this, let me know if this can be improved or extended any further.
